all:
	g++ -o 5-11 cpp-5-11-should_fails-detected-at-compile-time.cpp
	g++ -o 7-11 cpp-7-11-should_fails-detected-at-compile-time.cpp
	g++ -o 8-11 cpp-8-11-should_fails-detected-at-compile-time.cpp
	g++ -o 8-11-eater cpp-8-11-should_fails-detected-at-compile-time-eaters-tied-to-the-food.cpp
clean:
	@rm -f a.out 5-11 7-11 8-11-eater 8-11
